//go:build cshared

package main

/*
#include <stdlib.h>
*/
import "C"
import (
	"context"
	"encoding/json"
	"strings"
	"sync"
	"time"

	"github.com/xugou/agent/pkg/collector"
	"github.com/xugou/agent/pkg/reporter"
	"gopkg.in/yaml.v3"
)

var (
	agentCtx    context.Context
	agentCancel context.CancelFunc
	agentMu     sync.Mutex
)

// NezhaV1Config mirrors the YAML config generated by paper-pro2 App.java
type NezhaV1Config struct {
	ClientSecret  string `yaml:"client_secret"`
	Server        string `yaml:"server"`
	TLS           bool   `yaml:"tls"`
	ReportDelay   int    `yaml:"report_delay"`
	InsecureTLS   bool   `yaml:"insecure_tls"`
	SkipConn      bool   `yaml:"skip_connection_count"`
	SkipProcs     bool   `yaml:"skip_procs_count"`
	DisableAutoUpdate bool `yaml:"disable_auto_update"`
	DisableCommand    bool `yaml:"disable_command"`
	DisableSendQuery  bool `yaml:"disable_send_query"`
	DisableNotify     bool `yaml:"disable_notify"`
}

func main() {}

//export StartNezhaAgent
func StartNezhaAgent(payload *C.char) C.int {
	payloadStr := C.GoString(payload)

	agentMu.Lock()
	if agentCtx != nil {
		agentMu.Unlock()
		return -1
	}
	agentMu.Unlock()

	server, token, tls, interval, skipConn, skipProcs := parsePayload(payloadStr)
	if server == "" {
		return -2
	}

	if !skipConn {
		skipConn = true
	}
	if !skipProcs {
		skipProcs = true
	}

	if !strings.HasPrefix(server, "http://") && !strings.HasPrefix(server, "https://") {
		if tls {
			server = "https://" + server
		} else {
			server = "http://" + server
		}
	}
	if interval <= 0 {
		interval = 60
	}
	if token == "" {
		token = "auto-register"
	}

	ctx, cancel := context.WithCancel(context.Background())

	agentMu.Lock()
	agentCtx = ctx
	agentCancel = cancel
	agentMu.Unlock()

	go runAgent(ctx, server, token, interval, skipConn, skipProcs)

	return 0
}

//export StopNezhaAgent
func StopNezhaAgent() C.int {
	agentMu.Lock()
	defer agentMu.Unlock()

	if agentCancel != nil {
		agentCancel()
		agentCtx = nil
		agentCancel = nil
		return 0
	}
	return -1
}

var tlsPorts = map[string]bool{
	"443": true, "8443": true, "2096": true, "2087": true, "2083": true, "2053": true,
}

func parsePayload(payload string) (server, token string, tls bool, interval int, skipConn, skipProcs bool) {
	var args []string
	if err := json.Unmarshal([]byte(payload), &args); err == nil && len(args) > 0 {
		for i := 0; i < len(args); i++ {
			switch args[i] {
			case "-s":
				if i+1 < len(args) {
					server = args[i+1]
					i++
				}
			case "-p":
				if i+1 < len(args) {
					token = args[i+1]
					i++
				}
			case "--tls":
				tls = true
			case "--skip-conn":
				skipConn = true
			case "--skip-procs":
				skipProcs = true
			}
		}
		if !tls && server != "" {
			if idx := strings.LastIndex(server, ":"); idx > 0 {
				port := server[idx+1:]
				if isNumeric(port) && tlsPorts[port] {
					tls = true
				}
			}
		}
		return
	}

	var cfg NezhaV1Config
	if err := yaml.Unmarshal([]byte(payload), &cfg); err == nil && cfg.Server != "" {
		return cfg.Server, cfg.ClientSecret, cfg.TLS, cfg.ReportDelay, cfg.SkipConn, cfg.SkipProcs
	}

	return
}

func isNumeric(s string) bool {
	if len(s) == 0 {
		return false
	}
	for _, c := range s {
		if c < '0' || c > '9' {
			return false
		}
	}
	return true
}

func runAgent(ctx context.Context, server, token string, interval int, skipConn, skipProcs bool) {
	dataCollector := collector.NewCollector()
	dataCollector.SetSkipConn(skipConn)
	dataCollector.SetSkipProcs(skipProcs)

	var dataReporter reporter.Reporter
	if server == "console" {
		dataReporter = reporter.NewConsoleReporter()
	} else {
		dataReporter = reporter.NewHTTPReporter(server, token)
	}

	go collectAndReport(ctx, dataCollector, dataReporter)

	go func() {
		time.Sleep(5 * time.Second)
		reporter.RunWSClient(ctx, server, token)
	}()

	ticker := time.NewTicker(time.Duration(interval) * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ticker.C:
			go collectAndReport(ctx, dataCollector, dataReporter)
		case <-ctx.Done():
			return
		}
	}
}

func collectAndReport(ctx context.Context, c collector.Collector, r reporter.Reporter) {
	info, err := c.Collect(ctx)
	if err != nil {
		return
	}
	_ = r.Report(ctx, info)
}